version: '3.8'

services:
  form-dashboard:
    image: form-dashboard:latest
    build:
      context: ./form-dashboard
      dockerfile: Dockerfile
    ports:
      - "48620:3000"
    environment:
      NODE_ENV: production
      COOKIE_SECURE: 'true'
      NEXT_PUBLIC_API_URL: 'https://forms.newnet.com.br/extapi'
      NEXT_PUBLIC_WS_URL: 'wss://forms.newnet.com.br/extapi'
      NEXT_PUBLIC_FORM_URL: 'https://pesquisa.newnet.com.br'
    deploy:
      restart_policy:
        condition: on-failure

  client-form:
    image: client-form:latest
    build:
      context: ../client-form/client-form
      dockerfile: Dockerfile
    ports:
      - "48621:3000"
    environment:
      NEXT_PUBLIC_API_URL: 'https://forms.newnet.com.br/extapi'
    deploy:
      restart_policy:
        condition: on-failure
         
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: pesquisa_user
      POSTGRES_PASSWORD: supersegura123
      POSTGRES_DB: pesquisa_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    deploy:
      restart_policy: { condition: on-failure }

  backend:
    image: iamreinaldo/pesquisa-api:latest
    environment:
      DB_URL: postgresql://pesquisa_user:supersegura123@db:5432/pesquisa_db
      JWT_SECRET: dcb318f7bbc70f0294b56da4b35375f09febf4ef09a4c4538f261d64eef9e5b8
      MEDIA_ROOT: /app/media
      MEDIA_URL: /media
      MAX_IMAGE_SIZE_MB: "5"
      ALLOWED_IMAGE_TYPES: '["image/jpeg","image/png","image/webp"]'
      SECRET_KEY: supersegura
      RUN_MIGRATIONS: "0"
    ports:
      - "8000:8000"
    volumes:
      - media:/app/media
    deploy:
      restart_policy: { condition: on-failure }

volumes:
  pgdata:
  media:
