version: '3.8'

# Adicione esta seção para definir a rede
networks:
  app-net:
    driver: overlay

services:
  form-dashboard:
    # 1. Puxa a imagem genérica do seu Docker Hub
    image: gabrieulevi/form-dashboard:latest
    ports:
      - "48620:3000"
    environment:
      # --- Valores agora estão "hardcoded" ---
      NODE_ENV: "production"
      COOKIE_SECURE: "false"
      NEXT_PUBLIC_API_URL: "https://candol.cdldejacobina.com.br/extapi"
      NEXT_PUBLIC_WS_URL: "wss://candol.cdldejacobina.com.br/extapi"
      NEXT_PUBLIC_FORM_URL: "https://pesquisa.cdldejacobina.com.br"
    deploy:
      restart_policy:
        condition: on-failure
    networks:
      - app-net

  client-form:
    # 1. Puxa a imagem genérica
    image: gabrieulevi/client-form:latest
    ports:
      - "48621:3000"
    environment:
      # --- Valores agora estão "hardcoded" ---
      NODE_ENV: "production"
      NEXT_PUBLIC_API_URL: "https://candol.cdldejacobina.com.br/extapi" # (Ou qualquer URL que este cliente precise)
    deploy:
      restart_policy:
        condition: on-failure
    networks:
      - app-net

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: pesquisa_user
      POSTGRES_PASSWORD: supersegura123
      POSTGRES_DB: pesquisa_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U pesquisa_user -d pesquisa_db || exit 1"]
      interval: 5s
      timeout: 3s
      retries: 30
      start_period: 20s
    deploy:
      restart_policy: { condition: on-failure }
    # Conecte o serviço à nossa rede
    networks:
      - app-net

  backend:
    image: iamreinaldo/pesquisa-api:latest
    environment:
      DB_URL: postgresql://pesquisa_user:supersegura123@db:5432/pesquisa_db
      JWT_SECRET: dcb318f7bbc70f0294b56da4b35375f09febf4ef09a4c4538f261d64eef9e5b8
      MEDIA_ROOT: /app/media
      MEDIA_URL: /media
      MAX_IMAGE_SIZE_MB: "5"
      ALLOWED_IMAGE_TYPES: '["image/jpeg","image/png","image/webp"]'
      SECRET_KEY: supersegura
      RUN_MIGRATIONS: "0"
      UVICORN_RELOAD: "0"
    ports:
      - "8000:8000"
    volumes:
      - media:/app/media
    deploy:
      restart_policy: { condition: on-failure }
    # Conecte o serviço à nossa rede
    networks:
      - app-net

volumes:
  pgdata:
  media:
