version: '3.8'

services:
  form-dashboard:
    image: form-dashboard:latest
    build:
      context: ./form-dashboard
      dockerfile: Dockerfile
    ports:
      - "48620:3000"
    environment:
      NODE_ENV: production
      COOKIE_SECURE: 'false'
      NEXT_PUBLIC_API_URL: 'https://187.103.0.135:8000'
      NEXT_PUBLIC_WS_URL: 'wss://187.103.0.135:8000'
      NEXT_PUBLIC_FORM_URL: 'https://pesquisa.newnet.com.br'
    deploy:
      restart_policy:
        condition: on-failure

  client-form:
    image: client-form:latest
    build:
      context: ../client-form/client-form
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - ../client-form/client-form/.env.local
    deploy:
      restart_policy:
        condition: on-failure